stock_company_map = {
    'SCHW': ['SCHW', 'Charles Schwab', 'Schwab'],
    'MSFT': ['MSFT', 'Microsoft'],
    'BAC': ['BAC', 'bank of america', 'bofa'],
    'NEP': ['NEP', 'next era energy', 'nextera'],
    'GEN': ['GEN', 'gen digital'],
    'WHD': ['WHD', 'cactus'],
    'TSM': ['TSM', 'Taiwan Semiconductor'],
    'AMZN': ['AMZN', 'amazon'],
    'GOOGL': ['GOOGL', 'Google', 'Android'],
    'INTC': ['INTC', 'intel'],
    'JNJ': ['JNJ', 'johnson'],
    'GTX': ['GTX'],
    'AAPL': ['AAPL', 'apple inc.', 'apple'],
    'JPM': ['JPM', 'jp morgan', 'chase bank', 'morgan chase'],
    'RMR': ['RMR'],
    'PARA': ['PARA', 'paramount'],
    'ABCB': ['ABCB', 'abc bank', 'abc bancorp'],
    'MRK': ['MRK'],
    'RNGR': ['RNGR', 'ranger'],
    'PFS': ['PFS'],
    'PFE': ['PFE', 'Pfizer'],
    'DTC': ['DTC', 'solo brands'],
    'TOYOF': ['TOYOF', 'toyota'],
    'ATVI': ['ATVI', 'activision'],
    'PLTR': ['PLTR', 'Palantir'],
    'IMMR': ['IMMR', 'immersion'],
    'INMD': ['INMD', 'inmode'],
    'T': ['T', 'at&t'],
    'PDSB': ['PDSB'],
    'CVNA': ['CVNA', 'carvana'],
    'SOFI': ['SOFI', 'sofi bank'],
    'FITB': ['FITB', 'fifth third'],
    'GHM': ['GHM', 'graham corp'],
    'CPNG': ['CPNG', 'coupang'],
    'SLB': ['SLB', 'schlumberger'],
    'LUMN': ['LUMN', 'lumen'],
    'LILA': ['LILA'],
    'MNTK': ['MNTK', 'montauk']
}